name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: git clone https://gitlab.com/CentOS/automotive/sample-images.git && sudo sample-images/auto-image-builder.sh cs9-qemu-minimal-ostree.x86_64.qcow2

